version: '3.8'

services:
  app:
    build:
      context: ./php
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html          # Map Laravel files from local machine to container
      - ./src/storage:/var/www/html/storage  # Ensure storage permissions
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - db                           # app only depends on db, not web

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html          # Map Laravel files from local machine to container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app                          # web depends on app

  db:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
